apiVersion: v1
kind: Service
metadata:
  name: end-to-end-pipeline
  labels:
    app: end-to-end-pipeline
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
  selector:
    app: end-to-end-pipeline



